### ISSUE TITLE
randomly stops while downloading

### ISSUE THREAD

**Issue by Mundzso** [saurabhan/Wallhaven-dl#20]
I could not figure out what is happening. It runs into some kind of error, but seems to be random (I mean sometimes after 300 images sometimes after 450 etc...).
What could be the problem, some kind of timeout or something?

The error looks like this:
"Traceback (most recent call last):
  File "wallhaven-dl.py", line 130, in <module>
    main()
  File "wallhaven-dl.py", line 127, in main
    downloadPage(j, totalImageToDownload)
  File "wallhaven-dl.py", line 81, in downloadPage
    pagesImages = json.loads(urlreq.content);
  File "C:\Users\Xyz\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Xyz\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Xyz\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

**Comment by Mundzso** [comment]
not an issue any more
